# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "John Choque"

# A description of your site for social meta tag, search engines, and feed.xml
description: "I am passionate about Sustainable Development, Music and Productivity. Facilitator and builder on various projects on industry. Mental health and Gender Equality advocate. Good communicator and planner with a strong logical judgement, with experience at different international events and programs."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:  ""

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://yongt9412.com/"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "John Choque"

# Social links in the site footer
twitter_username:
facebook_username:
instagram_username:
linkedin_username: "john-choque-condori"

collections:
  projects:
    output: true
    permalink: /projects/:name

gems:
  - jekyll-paginate
paginate: 6
paginate_path: /blog2/:num/
